# Generated by Django 5.2.12 on 2026-04-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level (0–2 years)'), ('mid', 'Mid Level (2–5 years)'), ('senior', 'Senior Level (5+ years)'), ('any', 'Any Level')], default='any', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('douala', 'Douala'), ('yaounde', 'Yaoundé'), ('bafoussam', 'Bafoussam'), ('bamenda', 'Bamenda'), ('buea', 'Buea'), ('remote', 'Remote'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='tech_stacks',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.techstack'),
        ),
    ]
