# Generated by Django 5.2.12 on 2026-04-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_techstack_job_experience_level_alter_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (2-5 years)'), ('senior', 'Senior Level (5+ years)'), ('any', 'Any Level')], default='any', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('douala', 'Douala'), ('yaounde', 'Yaounde'), ('bafoussam', 'Bafoussam'), ('bamenda', 'Bamenda'), ('buea', 'Buea'), ('remote', 'Remote'), ('other', 'Other')], max_length=50),
        ),
    ]
