# Generated by Django 5.2.12 on 2026-04-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_payment_client_secret'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
