# Generated by Django 5.2.12 on 2026-04-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('jobs', '0002_techstack_job_experience_level_alter_job_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='seeker_photos/')),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Entry Level (0–2 years)'), ('mid', 'Mid Level (2–5 years)'), ('senior', 'Senior Level (5+ years)')], max_length=20)),
                ('availability', models.CharField(blank=True, choices=[('immediately', 'Immediately Available'), ('2weeks', 'Available in 2 Weeks'), ('1month', 'Available in 1 Month'), ('not_looking', 'Not Actively Looking')], max_length=20)),
                ('github', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('preferred_locations', models.CharField(blank=True, max_length=200)),
                ('job_alerts_enabled', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this seeker belongs to.', related_name='seeker_set', related_query_name='seeker', to='auth.group', verbose_name='groups')),
                ('preferred_categories', models.ManyToManyField(blank=True, related_name='seekers', to='jobs.category')),
                ('saved_jobs', models.ManyToManyField(blank=True, related_name='saved_by', to='jobs.job')),
                ('skills', models.ManyToManyField(blank=True, related_name='seekers', to='jobs.techstack')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this seeker.', related_name='seeker_set', related_query_name='seeker', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Job Seeker',
                'verbose_name_plural': 'Job Seekers',
            },
        ),
    ]
