# Generated by Django 5.2.12 on 2026-04-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (2-5 years)'), ('senior', 'Senior Level (5+ years)')], max_length=20),
        ),
    ]
